# Generated by Django 4.2.4 on 2023-08-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Query',
            new_name='Messege',
        ),
    ]
