# Generated by Django 4.2.4 on 2023-09-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_query_query_messege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Messege',
            new_name='Message',
        ),
    ]
