# Generated by Django 4.2.4 on 2023-09-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_messege_query_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Inquiry',
        ),
    ]
